env:
  PRETTIER_NODE_VERSION: 19.3.0

depends:
  - prettier-maven-plugin

before:
  - description: Fix nprmc
    commands:
      - cat /usr/share/hubspot/build/.npmrc | grep -v 'username = ' | grep -v  '_auth = ' > /tmp/nprmc
      - cat /tmp/nprmc > /usr/share/hubspot/build/.npmrc
